### ISSUE TITLE
Email Validation Not workin

### ISSUE THREAD

**Issue by SylviaPurcell** [anuragchaurasia/PurcCompanies#1]
Sales Person MadalynM@purcellcompliance.com she added a sale today and email validation would not let us save the file or submit.  We inputted multiple emails that we know are right and it still would say INVALID EMAIL .. we were unable to submit.  DOT number 3177262

**Comment by anuragchaurasia** [comment]
Fixed now. Please check

**Comment by SylviaPurcell** [comment]
I will try to test it.  was there an api issue or what was it?

**Comment by anuragchaurasia** [comment]
I wasn't disabling the validation after enable on wrong email. Now I disables when correct email.

**Comment by SylviaPurcell** [comment]
So was it only Maddys or do you need to do for everyone?

**Comment by anuragchaurasia** [comment]
Fixed for everyone.
