### ISSUE TITLE
MC Portal For Madalyn sales 

### ISSUE THREAD

**Issue by SylviaPurcell** [anuragchaurasia/PurcCompanies#3]
when she types in Legal Name it does not SAVE when she clicks submit .... 

It saves when she clicks saves

when she clicks submit before save ... it does not save and admin can not see the legal name

**Comment by anuragchaurasia** [comment]
Can you please let me know any customer USDOT# to check ?

**Comment by SylviaPurcell** [comment]
It is ALL of her MC Sales.. it is also doing it on my MC sales when I tested it on my name.  You can chose any MC Sale of Madalyns to test.

**Comment by anuragchaurasia** [comment]
Fixed Now.Please confirm so that we can close this.

**Comment by SylviaPurcell** [comment]
Confirmed FIXED / Tested
