### ISSUE TITLE
MC Auto populate for Second sale ( UPSEll ) 

### ISSUE THREAD

**Issue by SylviaPurcell** [anuragchaurasia/PurcCompanies#4]
Auto populate for address should populate in field Physical Address not Name on Card Address Field. (Done)  

We only want to see last 4 of credit card . (Done)

Need to see prior purchase. (Done) 

When I added a second service it ADDED THE PRIOR SERVICE TO THE NEW SECOND SERVICE. (done)

It should only add together new services.  See examples in Sales Sylvia portal DOT 3152233 Sale one and Sale Two.  (Done)

Somewhere we need to be able to identify that it is a second sale ( UpSell) for ADMIN and SALES 
<img width="1295" alt="screen shot 2018-08-25 at 1 02 12 pm" src="https://user-images.githubusercontent.com/42577425/44621664-1ad40300-a867-11e8-9517-f2059d6f502e.png">
<img width="711" alt="screen shot 2018-08-25 at 1 01 57 pm" src="https://user-images.githubusercontent.com/42577425/44621666-258e9800-a867-11e8-98cf-7e5ddbaa0933.png">

**Comment by anuragchaurasia** [comment]
Auto populate for address should populate in field Physical Address not Name on Card Address Field. **(Done)**

We only want to see last 4 of credit card . **(Done)**

Somewhere we need to be able to identify that it is a second sale ( UpSell) for SALES **(Done)**


When I look at it on ADMIN side LEGAL NAME did not SAVE **(Fixed)**

**Comment by SylviaPurcell** [comment]
THANK YOU!!!

**Comment by SylviaPurcell** [comment]
Tested MC UpSell  -  when I click on same on address on card the addresses delete instead of auto populating same address 

On admin side - they do not see the upsell information- they only see the prior information.

**Comment by SylviaPurcell** [comment]
Upsell on Admin we also need to see who the original sales person was...

**Comment by SylviaPurcell** [comment]
<img width="1398" alt="screen shot 2018-09-04 at 8 23 27 pm" src="https://user-images.githubusercontent.com/42577425/45067439-85afe600-b080-11e8-8405-fa8effed9b56.png">
<img width="1276" alt="screen shot 2018-09-04 at 8 23 20 pm" src="https://user-images.githubusercontent.com/42577425/45067440-85afe600-b080-11e8-9392-109ce6ab403f.png">

Here on the services it needs to read **Original Sale** instead of upsell - ( So this is prior service)

Then on  the new service added - This would say **UPSELL**

**Comment by SylviaPurcell** [comment]
We will do all this on USDOT SIDE ONY NOW
